// Generated by CoffeeScript 1.8.0
(function() {
  var coffeelint, through;

  through = require('through2');

  coffeelint = require('coffeelint');

  coffeelint.reporter = require('coffeelint-stylish').reporter;

  module.exports = function(file, options) {
    if (options == null) {
      options = {};
    }
    return through(function(buf, enc, next) {
      var errors;
      if (file.substr(-7) === '.coffee') {
        errors = coffeelint.lint(buf.toString('utf8'), options);
        if (errors.length !== 0) {
          coffeelint.reporter(file, errors);
        }
      }
      this.push(buf);
      return next();
    });
  };

}).call(this);
